# Generated by Django 3.2.12 on 2022-03-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_value', models.CharField(blank=True, max_length=250, null=True, verbose_name='Structure Value')),
                ('status', models.CharField(blank=True, max_length=250, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
    ]
