# Generated by Django 4.0.3 on 2022-03-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0002_alter_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
    ]
