# Generated by Django 4.0.3 on 2022-03-12 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search_terms', '0002_alter_search_terms_clicks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.TextField()),
                ('total_cost', models.IntegerField()),
                ('total_conversion_value', models.IntegerField()),
                ('roas', models.FloatField()),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_terms.search_terms')),
            ],
            options={
                'ordering': ['-roas'],
            },
        ),
    ]
