# Generated by Django 4.0.3 on 2022-03-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField(unique=True, verbose_name='campaign_id')),
                ('structure_value', models.TextField(verbose_name='structure_value')),
                ('status', models.CharField(max_length=7, verbose_name='status')),
            ],
        ),
    ]
