# Generated by Django 4.0.3 on 2022-03-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_terms',
            name='clicks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='search_terms',
            name='conversion_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='search_terms',
            name='conversions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='search_terms',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='search_terms',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='search_terms',
            name='search_term',
            field=models.TextField(blank=True, null=True),
        ),
    ]
