# Generated by Django 4.0.3 on 2022-03-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file',
            field=models.FileField(upload_to='./csvfiles'),
        ),
    ]
