# Generated by Django 4.0.3 on 2022-03-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adgroups', '0002_alter_adgroups_ad_group_id_alter_adgroups_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroups',
            name='ad_group_id',
            field=models.TextField(),
        ),
    ]
